# SPDX-FileCopyrightText: Copyright (C) swift Project Community / Contributors
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "swift pilotclient"
SPDX-PackageDownloadLocation = "https://github.com/swift-project/pilotclient"

[[annotations]]
path = "scripts/csl2xsb/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2019 B.Hoppe"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/gui/**.ui"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "CMakePresets.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "version.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/misc/icons/vatsim/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "src/misc/icons/diagona/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2013 Yusuke Kamiyamane. All rights reserved."
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = "src/misc/icons/pastel/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The Pastel SVG icon set Created by Michael Buckley"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"

[[annotations]]
path = "src/misc/icons/qled/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Jean-Victor Balin"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "src/misc/icons/own/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/misc/icons/textures/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "src/swiftlauncher/icons/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "installer/images/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftcore/data.rc"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftcore/swiftcore.icns"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftcore/swiftcore.ico"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftdata/data.rc"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftdata/swiftdata.icns"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftdata/swiftdata.ico"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftguistandard/data.rc"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftguistandard/swift.icns"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftguistandard/swift.ico"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftlauncher/data.rc"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftlauncher/swiftlauncher.icns"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/swiftlauncher/swiftlauncher.ico"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/xswiftbus/datarefs.inc"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "src/xswiftbus/LegacyData/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "src/sound/share/sounds/afv_click_f32.wav"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) Christopher Collins; From AFV-Native"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "src/sound/share/sounds/afv_crackle_f32.wav"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) Christopher Collins; From AFV-Native"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "src/sound/share/sounds/afv_hf_whiteNoise_f32.wav"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) Christopher Collins; From AFV-Native"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "src/sound/share/sounds/afv_whitenoise_f32.wav"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) Christopher Collins; From AFV-Native"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "src/xswiftbus/org.swift_project.xswiftbus.service.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"

[[annotations]]
path = "src/xswiftbus/org.swift_project.xswiftbus.traffic.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) swift Project Community / Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1"
