#include "atcmanager.h"
#include "blackcore/dbusserver.h"

#include "atcmanagerhandler.h"

// It is really IMPORTANT to include this header.
// Otherwise it won't be generated by qmake and the
// project can't be build
#include "atcmanager_adaptor.h"

CAtcManagerHandler::CAtcManagerHandler(QObject *parent) :
    QObject(parent), m_dbusserver(0), m_parent(0)
{
    m_dbusPath = "/AtcManager";
    m_parent = qobject_cast<CAtcManager *>(parent);

    new AtcManagerAdaptor(this);
}

CAtcManagerHandler::~CAtcManagerHandler()
{

}

void CAtcManagerHandler::setDBusServer(BlackCore::CDBusServer *dbusServer)
{
    m_dbusserver = dbusServer;

    if (m_dbusserver)
        m_dbusserver->addObject(m_dbusPath, this);
}

QStringList CAtcManagerHandler::atcList() const
{
    qDebug() << "Somebody requested the list of controllers. Here you go...";
    return m_parent->atcList();
}
