/*  Copyright (C) 2013 VATSIM Community / contributors
 *  This Source Code Form is subject to the terms of the Mozilla Public
 *  License, v. 2.0. If a copy of the MPL was not distributed with this
 *  file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "blackcore/dbus_server.h"
#include "fsd_client_handler.h"
#include "fsd_client.h"

/**
 * It is really IMPORTANT to include the following header.
 * Otherwise it won't be generated by qmake and the
 * project can't be build
 */
#include "fsdclient_adaptor.h"

CFsdClientHandler::CFsdClientHandler(QObject *parent) :
    IDBusHandler(parent)
{
    setDBusObjectPath("/FsdClient");
    new FsdClientAdaptor(this);
}

void CFsdClientHandler::connectTo(const QString &host)
{
    CFsdClient *fsdClient = qobject_cast<CFsdClient*>(m_parent);
    fsdClient->connectTo(host);
    emit connectedTo(host);
}
