# SPDX-FileCopyrightText: Copyright (C) swift Project Community / Contributors
# SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-swift-pilot-client-1

# This file contains definitions for all PCHs.
# The definitions are collected because targets might reuse headers from another target and also adds own headers.
# For example "core" uses the same PCH as "misc" but with additional headers included.

set(SWIFT_MISC_PCH
    [["misc/collection.h"]]
    [["misc/dbus.h"]]
    [["misc/dictionary.h"]]
    [["misc/json.h"]]
    [["misc/metaclass.h"]]
    [["misc/sequence.h"]]
    [["misc/valueobject.h"]]
    [["misc/verify.h"]]

    <QByteArray>
    <QDBusArgument>
    <QDBusMetaType>
    <QDateTime>
    <QDir>
    <QFile>
    <QFlags>
    <QHash>
    <QIcon>
    <QJsonArray>
    <QJsonObject>
    <QJsonValue>
    <QJsonValueRef>
    <QLatin1String>
    <QList>
    <QLoggingCategory>
    <QMap>
    <QMessageLogContext>
    <QMetaObject>
    <QMetaType>
    <QMutex>
    <QObject>
    <QPair>
    <QPixmap>
    <QReadWriteLock>
    <QScopedPointer>
    <QSet>
    <QSharedPointer>
    <QString>
    <QStringBuilder>
    <QStringList>
    <QStringRef>
    <QThread>
    <QTime>
    <QTimer>
    <QVariant>
    <QVector>
    <QtGlobal>

    <algorithm>
    <cmath>
    <exception>
    <functional>
    <future>
    <initializer_list>
    <iterator>
    <map>
    <memory>
    <set>
    <string>
    <tuple>
    <type_traits>
    <typeindex>
    <utility>
    <vector>
)

set(SWIFT_CORE_PCH
    <QDBusAbstractInterface>
    <QDBusConnection>
    <QDBusConnectionInterface>
    <QDBusError>
    <QDBusMessage>
    <QDBusPendingCall>
    <QDBusPendingReply>
    <QDBusReply>
    <QDBusServer>
    <QDBusServiceWatcher>
    <QNetworkAccessManager>
    <QNetworkCookieJar>
    <QNetworkInterface>
    <QNetworkReply>
    <QNetworkRequest>
    <QUrl>
)

set(SWIFT_GUI_PCH
    [["core/context/contextapplication.h"]]
    [["core/context/contextaudio.h"]]
    [["core/context/contextnetwork.h"]]
    [["core/context/contextownaircraft.h"]]
    [["core/context/contextsimulator.h"]]

    <QAbstractButton>
    <QAbstractItemModel>
    <QAbstractItemView>
    <QAbstractScrollArea>
    <QAbstractTableModel>
    <QComboBox>
    <QDialog>
    <QDockWidget>
    <QDrag>
    <QDragEnterEvent>
    <QDragLeaveEvent>
    <QDragMoveEvent>
    <QDropEvent>
    <QFrame>
    <QImage>
    <QLabel>
    <QLayout>
    <QLayoutItem>
    <QLineEdit>
    <QMenu>
    <QMenuBar>
    <QMessageBox>
    <QPoint>
    <QPushButton>
    <QRadioButton>
    <QRect>
    <QSize>
    <QSlider>
    <QSplitter>
    <QStackedWidget>
    <QStyle>
    <QTabBar>
    <QTabWidget>
    <QTableView>
    <QTextEdit>
    <QValidator>
    <QWidget>
    <QWindow>
)
