# SPDX-FileCopyrightText: Copyright (C) swift Project Community / Contributors
# SPDX-License-Identifier: CC0-1.0

name: Build swift

on:
  merge_group:
    branches: [main]
  workflow_dispatch: # manually triggered

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  do_symbols:    ${{ github.event_name == 'merge_group' }}
  qt_version:    &qt_version 6.11.1
  bitrock_version: qt-professional-25.10.1
  bitrock_url:     https://releases.installbuilder.com/installbuilder
  installbuilder_hash_win: f92b1741c78b8f024473f55057b26107c8ed9cc1ca583eb9323d0023a8024e00
  installbuilder_hash_linux: 3dff24cf94af17158cbcb16af41ecf0bb5060ba97d052597f15b987bd5e5b43a
  installbuilder_hash_macos: bffa8b2663c6e9aaaa1ed7cdb41a874d34ff89f22adfab419e172915f8f4ce57
  externals: swift-project/externals
  externals_sha: e1f1743ba159e11b0c065ea8f1ae1a0e91e3bf39

jobs:

  preBuild:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.value }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
      - name: Get version number
        id: version
        run: |
          echo "value=$(python3 -u scripts/utils.py --version)" >>$GITHUB_OUTPUT
      - name: Remove artifacts
        uses: swift-project/delete-artifact@swift
        with:
          name: |
            xswiftbus-thin-*
            xswiftbus-fat-*
            swiftsymbols-*
            swiftinstaller-*
          failOnError: false
          warnIfNotFound: false

  checks:
    uses: ./.github/workflows/reusable_checks.yml

  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: '0'
      - name: Check if clang-tidy analysis is required
        id: check_need_clang_tidy
        run: |
          if python3 -u scripts/run_static_analysis.py --check-changed-files; then
            echo "should_run_clang_tidy=false" >> $GITHUB_OUTPUT
          else
            echo "should_run_clang_tidy=true" >> $GITHUB_OUTPUT
          fi
      - name: Checkout repository
        if: ${{ steps.check_need_clang_tidy.outputs.should_run_clang_tidy == 'true' }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: '0'
          submodules: 'true'
      - name: Install Qt
        if: ${{ steps.check_need_clang_tidy.outputs.should_run_clang_tidy == 'true' }}
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730
        with:
          version: ${{ env.qt_version }}
          modules: 'qtmultimedia'
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git@8c3695d4a4e1ceabf6a74dc6c79681656dc6b74b'
          cache: true
      - name: Install dependencies
        if: ${{ steps.check_need_clang_tidy.outputs.should_run_clang_tidy == 'true' }}
        run: |
          sudo apt-get -y install dbus-x11 libglu1-mesa-dev libpulse-dev libdbus-1-dev ninja-build
          pip3 install requests conan==2.29.1
      - name: Checkout externals
        if: ${{ steps.check_need_clang_tidy.outputs.should_run_clang_tidy == 'true' }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        env:
          EXTERNALS_PAT: ${{ secrets.EXTERNALS_PAT }}
        with:
          repository: ${{ env.externals }}
          ref: ${{ env.externals_sha }}
          token: ${{ env.EXTERNALS_PAT }}
          path: 'third_party/externals'
      - name: Install conan dependencies
        if: ${{ steps.check_need_clang_tidy.outputs.should_run_clang_tidy == 'true' }}
        shell: bash
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: |
          conan remote disable conancenter
          conan remote add swift https://artifactory.swift-project.org/artifactory/api/conan/conan-local
          conan remote login swift "$ARTIFACTORY_USER" --password "$ARTIFACTORY_TOKEN"
          conan install . --output-folder=build_conan --deployer=full_deploy -pr:h=ci/profile_linux -pr:b=ci/profile_linux
      - name: Run clang-tidy
        if: ${{ steps.check_need_clang_tidy.outputs.should_run_clang_tidy == 'true' }}
        shell: bash
        run: |
          mkdir build && pushd build
          cmake .. --preset ci-build-linux-no-pch
          popd
          python3 scripts/run_static_analysis.py --clang-tidy --build-path build --changed-files-ci

  buildLinux:
    runs-on: ubuntu-24.04
    needs: [preBuild, checks, clang-tidy]
    env:
      BACKTRACE_SYMBOL_TOKEN: ${{ secrets.BACKTRACE_SYMBOL_TOKEN }}
      BACKTRACE_MINIDUMP_TOKEN: ${{ secrets.BACKTRACE_MINIDUMP_TOKEN }}
      BITROCK_BUILDER: ~/installbuilder/bin/builder
      SCCACHE_BUCKET: ${{ vars.SCCACHE_BUCKET }}
      SCCACHE_ENDPOINT: ${{ vars.SCCACHE_ENDPOINT }}
      SCCACHE_REGION: ${{ vars.SCCACHE_REGION }}
      AWS_EC2_METADATA_DISABLED: true
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SCCACHE_S3_NO_CREDENTIALS: false
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730
        with:
          version: ${{ env.qt_version }}
          modules: 'qtmultimedia'
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git@8c3695d4a4e1ceabf6a74dc6c79681656dc6b74b'
          cache: true
      - uses: cargo-bins/cargo-binstall@ead08b90bd7b2e6d81963fb9cf0b7239f66d5db4
        with:
          version: "1.20.1"
      - name: Cache InstallBuilder
        id: cache-bitrock
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/installbuilder.run
          key: installbuilder-${{ env.bitrock_version }}-linux-x64
      - name: Download InstallBuilder
        if: steps.cache-bitrock.outputs.cache-hit != 'true'
        run: |
          wget --retry-connrefused -t 10 -w 10 -T 60 -O ~/installbuilder.run ${{ env.bitrock_url }}/installbuilder-${{ env.bitrock_version }}-linux-x64-installer.run
          echo "${{ env.installbuilder_hash_linux }}  $HOME/installbuilder.run" | sha256sum -c -
      - name: Install InstallBuilder
        run: |
          chmod 700 ~/installbuilder.run
          ~/installbuilder.run --mode unattended --prefix ~/installbuilder
          cat >~/license.xml <<EOF
          $BITROCK_LICENSE
          EOF
        env:
          BITROCK_LICENSE: ${{ secrets.BITROCK_LICENSE }}
      - name: Install dependencies
        run: |
          sudo apt-get -y install dbus-x11 libglu1-mesa-dev libpulse-dev libdbus-1-dev ninja-build
          pip3 install requests conan==2.29.1
          cargo binstall sccache
      - name: Start sccache
        run: |
           sccache --start-server
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: true
          fetch-depth: 0
      - name: Checkout externals
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        env:
          EXTERNALS_PAT: ${{ secrets.EXTERNALS_PAT }}
        with:
          repository: ${{ env.externals }}
          ref: ${{ env.externals_sha }}
          token: ${{ env.EXTERNALS_PAT }}
          path: 'third_party/externals'
      - name: Install conan dependencies
        shell: bash
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: |
          conan remote disable conancenter
          conan remote add swift https://artifactory.swift-project.org/artifactory/api/conan/conan-local
          conan remote login swift "$ARTIFACTORY_USER" --password "$ARTIFACTORY_TOKEN"
          conan install . --output-folder=build_conan --deployer=full_deploy -pr:h=ci/profile_linux -pr:b=ci/profile_linux
      - name: Start DBus session bus
        run: |
          dbus-launch --sh-syntax | tee session.sh
          eval $(cat session.sh)
          echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS" >>$GITHUB_ENV
      - name: Create Vatsim key file
        run: |
          cat >vatsim.json <<EOF
          { "vatsim": { "id": "$VATSIM_ID", "key": "$VATSIM_KEY" } }
          EOF
        env:
          VATSIM_ID: ${{ secrets.VATSIM_ID }}
          VATSIM_KEY: ${{ secrets.VATSIM_KEY }}
      - uses: swift-project/setup-cpp@swift
      - name: Build swift (without symbols)
        if: ${{ env.do_symbols != 'true' }}
        run: |
          python3 -u scripts/build.py -w 64 -t gcc
      - name: Build swift (with symbols)
        if: ${{ env.do_symbols == 'true' }}
        run: |
          python3 -u scripts/build.py -w 64 -t gcc --upload-symbols
      - name: Stop sccache
        run: |
           sccache --stop-server
      - name: Upload installer
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: swiftinstaller-linux-64-${{ needs.preBuild.outputs.version }}
          path: ${{ github.workspace }}/swiftinstaller-*
      - name: Upload symbols
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: ${{ env.do_symbols == 'true' }}
        with:
          name: swiftsymbols-linux-64-${{ needs.preBuild.outputs.version }}
          path: ${{ github.workspace }}/swiftsymbols-*
      - name: Upload xswiftbus
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: xswiftbus-thin-linux-64-${{ needs.preBuild.outputs.version }}
          path: ${{ github.workspace }}/xswiftbus-*

  buildWin64:
    runs-on: windows-2025-vs2026
    needs: [preBuild, checks, clang-tidy]
    env:
      BACKTRACE_SYMBOL_TOKEN: ${{ secrets.BACKTRACE_SYMBOL_TOKEN }}
      BACKTRACE_MINIDUMP_TOKEN: ${{ secrets.BACKTRACE_MINIDUMP_TOKEN }}
      BITROCK_BUILDER: "~/installbuilder/bin/builder-cli.exe"
      SCCACHE_BUCKET: ${{ vars.SCCACHE_BUCKET }}
      SCCACHE_ENDPOINT: ${{ vars.SCCACHE_ENDPOINT }}
      SCCACHE_REGION: ${{ vars.SCCACHE_REGION }}
      AWS_EC2_METADATA_DISABLED: true
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SCCACHE_S3_NO_CREDENTIALS: false
      SCCACHE_LOG: debug
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730
        with:
          version: ${{ env.qt_version }}
          modules: 'qtmultimedia'
          arch: win64_msvc2022_64
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git@8c3695d4a4e1ceabf6a74dc6c79681656dc6b74b'
          cache: true
      - name: Install Qt debug info
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730
        with:
          version: ${{ env.qt_version }}
          arch: win64_msvc2022_64
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git@8c3695d4a4e1ceabf6a74dc6c79681656dc6b74b'
          cache: true
          modules: debug_info
          extra: --archives qtbase
      - uses: cargo-bins/cargo-binstall@ead08b90bd7b2e6d81963fb9cf0b7239f66d5db4
        with:
          version: "1.20.1"
      - name: Cache InstallBuilder
        id: cache-bitrock
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: C:\installbuilder.exe
          key: installbuilder-${{ env.bitrock_version }}-windows-x64
      - name: Download InstallBuilder
        if: steps.cache-bitrock.outputs.cache-hit != 'true'
        shell: C:\msys64\usr\bin\bash.exe -le {0}
        run: |
          wget --retry-connrefused -t 10 -w 10 -T 60 -O /c/installbuilder.exe ${{ env.bitrock_url }}/installbuilder-${{ env.bitrock_version }}-windows-x64-installer.exe
          echo "${{ env.installbuilder_hash_win }}  /c/installbuilder.exe" | sha256sum -c -
        env:
          MSYSTEM: MSYS2
      - name: Install InstallBuilder
        run: |
          start -wait "C:\installbuilder.exe" @("--mode", "unattended", "--prefix", "$HOME\installbuilder")
          echo >$HOME\license.xml @"
          $env:BITROCK_LICENSE
          "@
        env:
          BITROCK_LICENSE: ${{ secrets.BITROCK_LICENSE }}
      - name: Install dependencies
        run: |
          pip install requests PyInstaller conan==2.29.1
          cargo binstall sccache
      - name: Start sccache
        run: |
           sccache --start-server
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: true
          fetch-depth: 0
      - name: Checkout externals
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        env:
          EXTERNALS_PAT: ${{ secrets.EXTERNALS_PAT }}
        with:
          repository: ${{ env.externals }}
          ref: ${{ env.externals_sha }}
          token: ${{ env.EXTERNALS_PAT }}
          path: 'third_party/externals'
      - name: Install conan dependencies
        shell: bash
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: |
          conan remote disable conancenter
          conan remote add swift https://artifactory.swift-project.org/artifactory/api/conan/conan-local
          conan remote login swift "$ARTIFACTORY_USER" --password "$ARTIFACTORY_TOKEN"
          conan install . --output-folder=build_conan --deployer=full_deploy -pr:h=ci/profile_win -pr:b=ci/profile_win
      - name: Create Vatsim key file
        run: |
          echo >vatsim.json @"
          { "vatsim": { "id": "$env:VATSIM_ID", "key": "$env:VATSIM_KEY" } }
          "@
        env:
          VATSIM_ID: ${{ secrets.VATSIM_ID }}
          VATSIM_KEY: ${{ secrets.VATSIM_KEY }}
      - uses: swift-project/setup-cpp@swift
      - name: Build swift (without symbols)
        if: ${{ env.do_symbols != 'true' }}
        shell: cmd
        run: |
          build_conan\\build\\RelWithDebInfo\\generators\\conanrun.bat && python -u scripts/build.py -w 64 -t msvc
      - name: Build swift (with symbols)
        if: ${{ env.do_symbols == 'true' }}
        shell: cmd
        run: |
          build_conan\\build\\RelWithDebInfo\\generators\\conanrun.bat && python -u scripts/build.py -w 64 -t msvc --upload-symbols
      - name: Stop sccache
        run: |
           sccache --stop-server
      - name: Upload installer
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: swiftinstaller-windows-64-${{ needs.preBuild.outputs.version }}
          path: ${{ github.workspace }}/swiftinstaller-*
      - name: Upload symbols
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: ${{ env.do_symbols == 'true' }}
        with:
          name: swiftsymbols-windows-64-${{ needs.preBuild.outputs.version }}
          path: ${{ github.workspace }}/swiftsymbols-*
      - name: Upload xswiftbus
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: xswiftbus-thin-windows-64-${{ needs.preBuild.outputs.version }}
          path: ${{ github.workspace }}/xswiftbus-*

  buildMacOS:
    runs-on: macos-26
    needs: [preBuild, checks, clang-tidy]
    env:
      BACKTRACE_SYMBOL_TOKEN: ${{ secrets.BACKTRACE_SYMBOL_TOKEN }}
      BACKTRACE_MINIDUMP_TOKEN: ${{ secrets.BACKTRACE_MINIDUMP_TOKEN }}
      BITROCK_BUILDER: /Applications/installbuilder/bin/Builder.app/Contents/MacOS/installbuilder.sh
      SCCACHE_BUCKET: ${{ vars.SCCACHE_BUCKET }}
      SCCACHE_ENDPOINT: ${{ vars.SCCACHE_ENDPOINT }}
      SCCACHE_REGION: ${{ vars.SCCACHE_REGION }}
      AWS_EC2_METADATA_DISABLED: true
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SCCACHE_S3_NO_CREDENTIALS: false
      SCCACHE_LOG: debug

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730
        with:
          version: ${{ env.qt_version }}
          modules: 'qtmultimedia'
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git@8c3695d4a4e1ceabf6a74dc6c79681656dc6b74b'
          cache: true
      - uses: cargo-bins/cargo-binstall@ead08b90bd7b2e6d81963fb9cf0b7239f66d5db4
        with:
          version: "1.20.1"
      - name: Cache InstallBuilder
        id: cache-bitrock
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/installbuilder.dmg
          key: installbuilder-${{ env.bitrock_version }}-osx
      - name: Download InstallBuilder
        if: steps.cache-bitrock.outputs.cache-hit != 'true'
        run: |
          wget --retry-connrefused -t 10 -w 10 -T 60 -O $HOME/installbuilder.dmg ${{ env.bitrock_url }}/installbuilder-${{ env.bitrock_version }}-osx-installer.dmg
          echo "${{ env.installbuilder_hash_macos }}  $HOME/installbuilder.dmg" | sha256sum -c -
      - name: Install InstallBuilder
        run: |
          hdiutil attach $HOME/installbuilder.dmg
          cp -rf "/Volumes/InstallBuilder Qt/installbuilder-${{ env.bitrock_version }}-osx-installer.app" /Applications
          hdiutil detach "/Volumes/InstallBuilder Qt"
          sudo xattr -r -d com.apple.quarantine /Applications/installbuilder-${{ env.bitrock_version }}-osx-installer.app
          sudo /Applications/installbuilder-${{ env.bitrock_version }}-osx-installer.app/Contents/MacOs/installbuilder.sh --mode unattended --prefix /Applications/installbuilder
          cat >~/license.xml <<EOF
          $BITROCK_LICENSE
          EOF
        env:
          BITROCK_LICENSE: ${{ secrets.BITROCK_LICENSE }}
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip3 install requests conan==2.29.1
          cargo binstall sccache
      - name: Start sccache
        run: |
           sccache --start-server
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: true
          fetch-depth: 0
      - name: Checkout externals
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        env:
          EXTERNALS_PAT: ${{ secrets.EXTERNALS_PAT }}
        with:
          repository: ${{ env.externals }}
          ref: ${{ env.externals_sha }}
          token: ${{ env.EXTERNALS_PAT }}
          path: 'third_party/externals'
      - name: Install conan dependencies
        shell: bash
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: |
          # Empty presets to avoid autogenerated config from Conan
          echo "{\"version\": 6}" > CMakeUserPresets.json
          conan remote disable conancenter
          conan remote add swift https://artifactory.swift-project.org/artifactory/api/conan/conan-local
          conan remote login swift "$ARTIFACTORY_USER" --password "$ARTIFACTORY_TOKEN"
          conan install . --output-folder=build_conan --deployer=full_deploy -pr:h=ci/profile_mac -pr:b=ci/profile_mac_arm
          conan install . --output-folder=build_conan_arm --deployer=full_deploy -pr:h=ci/profile_mac_arm -pr:b=ci/profile_mac_arm
          # https://doc.qt.io/qt-6/macos-issues.html#d-bus-and-macos
          conan install --requires=dbus/1.15.8 --output-folder build_conan_dbus_shared --deployer=full_deploy -o "dbus/*:shared=True" -o "dbus/*:message_bus=True" -pr:h=ci/profile_mac -pr:b=ci/profile_mac_arm
      - name: Create Vatsim key file
        run: |
          cat >vatsim.json <<EOF
          { "vatsim": { "id": "$VATSIM_ID", "key": "$VATSIM_KEY" } }
          EOF
        env:
          VATSIM_ID: ${{ secrets.VATSIM_ID }}
          VATSIM_KEY: ${{ secrets.VATSIM_KEY }}
      - uses: swift-project/setup-cpp@swift
      - name: Build swift (without symbols)
        if: ${{ env.do_symbols != 'true' }}
        run: |
          python3 -u scripts/build.py -w 64 -t clang
      - name: Build swift (with symbols)
        if: ${{ env.do_symbols == 'true' }}
        run: |
          python3 -u scripts/build.py -w 64 -t clang --upload-symbols
      - name: Stop sccache
        run: |
           sccache --stop-server
      - name: Upload installer
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: swiftinstaller-macos-64-${{ needs.preBuild.outputs.version }}
          path: ${{ github.workspace }}/swiftinstaller-*
      - name: Upload symbols
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: ${{ env.do_symbols == 'true' }}
        with:
          name: swiftsymbols-macos-64-${{ needs.preBuild.outputs.version }}
          path: ${{ github.workspace }}/swiftsymbols-*
      - name: Upload xswiftbus
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: xswiftbus-thin-macos-64-${{ needs.preBuild.outputs.version }}
          path: ${{ github.workspace }}/xswiftbus-*

  postBuild:
    runs-on: ubuntu-24.04
    needs: [preBuild, checks, clang-tidy, buildLinux, buildWin64, buildMacOS]

    steps:
      - name: Download xswiftbus-thin
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          pattern: xswiftbus-thin-*
          merge-multiple: true
      - name: Repackage xswiftbus
        run: |
          unzip -o xswiftbus-windows-64-*.zip
          unzip -o xswiftbus-linux-64-*.zip
          unzip -o xswiftbus-macos-64-*.zip
          zip -r -9 xswiftbus-fat-allos-${{ needs.preBuild.outputs.version }}.zip xswiftbus
      - name: Upload xswiftbus-fat
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: xswiftbus-fat-allos-${{ needs.preBuild.outputs.version }}
          path: xswiftbus-fat-allos-*
      - name: Remove xswiftbus-thin artifacts
        uses: swift-project/delete-artifact@swift
        with:
          name: xswiftbus-thin-*

  notify:
    runs-on: ubuntu-24.04
    needs: [preBuild, checks, clang-tidy, buildLinux, buildWin64, buildMacOS, postBuild]
    if: always()

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y install jo jq
      - name: Query GitHub annotations
        uses: octokit/request-action@3d6703deef41a82916a2e5ca87096f93035cef66
        id: checkruns
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/swift-project/pilotclient/commits/${{ github.sha }}/check-runs
      - name: Prepare Discord build message
        run: |
          result=SKIPPED
          ${{ contains(needs.*.result, 'success')   }} && result=SUCCESS
          for run in $CHECK_RUNS; do
            curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/swift-project/pilotclient/check-runs/$run/annotations" \
            | jq -e 'any(.[].annotation_level; . == "warning" or . == "error")' && result=WARNING
          done
          ${{ contains(needs.*.result, 'cancelled') }} && result=CANCELLED
          ${{ contains(needs.*.result, 'failure')   }} && result=FAILED
          [[ $result = SKIPPED   ]] && emoji=repeat
          [[ $result = SUCCESS   ]] && emoji=white_check_mark
          [[ $result = WARNING   ]] && emoji=warning
          [[ $result = CANCELLED ]] && emoji=grey_question
          [[ $result = FAILED    ]] && emoji=x
          echo "result=$result"  >>$GITHUB_ENV
          echo "emoji=$emoji"    >>$GITHUB_ENV
        env:
          CHECK_RUNS: ${{ join(fromJson(steps.checkruns.outputs.data).check_runs.*.id, ' ') }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send Discord build message
        run: |
          cat >message <<EOF
          > :${{ env.emoji }}: \`${{ github.ref }}\`
          > **${{ env.result }}** (triggered by ${{ github.event_name }})
          > <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>
          EOF
          jo content=@message | curl -i -H "Accept: application/json" -H "Content-Type: application/json" $WEBHOOK -d @-
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
