# SPDX-FileCopyrightText: Copyright (C) swift Project Community / Contributors
# SPDX-License-Identifier: CC0-1.0

name: Pull request validation

on:
  pull_request:

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  qt_version:    &qt_version 6.11.1

jobs:
  checks:
    uses: ./.github/workflows/reusable_checks.yml

  doxygen:
    uses: ./.github/workflows/reusable_doxygen.yml
    with:
      upload_doxygen: false
      qt_version: *qt_version

  postBuild: # just a job with the same name as in the merge queue build to satisfy requirements
    runs-on: ubuntu-latest
    needs: [checks, doxygen]
    steps:
      - run: true
